const CONFIG = {
  GNEWS_API_KEY: 'YOUR_GNEWS_API_KEY',
  OPENWEATHER_API_KEY: 'YOUR_OPENWEATHERMAP_API_KEY',
  APIFOOTBALL_API_KEY: 'YOUR_APIFOOTBALL_API_KEY',
  EXCHANGERATE_API_KEY: 'YOUR_EXCHANGERATE_API_KEY',
  // Default league: English Premier League
  DEFAULT_LEAGUE_ID: '152'
};
